ethereum:
  NODE_URL: https://eth-mainnet.alchemyapi.io/v2/
  API_URL: https://api.etherscan.io/api?
contracts:
 - "0x7937d4799803fbbe595ed57278bc4ca21f3bffcb"
 - "0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9"
