name: Lint SQL

on:
  push:
    branches:
    - main
    paths:
    - '*.sql'

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
        architecture: x64
    - name: Install SQLFluff
      run: "pip install sqlfluff==0.3.6"
    - name: Lint .sql files
      run: "sqlfluff lint"
