name: Lint SQL

on:
  push:
    branches:
    - main
    paths:
    - '*.sql'

jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout_repo
      uses: actions/checkout@v2

    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
        architecture: x64

    - name: Install SQLFluff
      id: install_sqlfluff
      run: pip install sqlfluff==0.3.6

    - name: Get changed .sql files
      id: get_files_to_lint
      shell: bash -l {0}
      run: |
        # Set the command in the $() brackets as an output to use in later steps
        echo "::set-output name=lintees::$(
        # Issue where grep regular expressions don't work as expected on the
        # Github Actions shell, check dbt/models/ folder
        echo \
        $(echo ${{ steps.get_file_changes.outputs.files_modified }} |
        tr -s ' ' '\n' |
        grep -E '*[.]sql$' |
        tr -s '\n' ' ') \
        $(echo ${{ steps.get_file_changes.outputs.files_added }} |
        tr -s ' ' '\n' |
        grep -E '*[.]sql$' |
        tr -s '\n' ' ')
        )"

    - name: Lint .sql files
      id: lint_sql_files
      run: sqlfluff lint --format github-annotation --annotation-level failure --nofail ${{ steps.get_files_to_lint.outputs.lintees }} > annotations.json
