name: Lint Python

on:
  push:
    branches:
    - main
    paths:
    - '*.py'

jobs:
  run_flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout_repo
      uses: actions/checkout@v2

    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
        architecture: x64

    - name: Install flake8
      run: pip install flake8

    - name: Lint .py files
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'run_flake8'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
